# Notebook 05 – Power BI Churn Retention Dashboard

## Purpose

This notebook prepares the outputs from the customer churn analytics project for executive dashboard reporting in Power BI.

Following the completion of:

- Data preparation
- Exploratory data analysis
- SQL business analysis
- Machine learning churn prediction

this stage focuses on transforming analytical results into business intelligence datasets.

## Objectives

The objectives of this notebook are:

- Load the cleaned customer dataset
- Import machine learning prediction outputs
- Create Power BI-ready reporting tables
- Validate data quality and consistency
- Prepare datasets for dashboard development

## Data Inputs

### Customer Dataset

Source:
Notebook 01 – Data Cleaning & Preparation

Includes:

- Customer demographics
- Subscription details
- Revenue information
- Customer engagement metrics
- Support experience metrics
- Churn outcome

### Machine Learning Outputs

Source:
Notebook 04 – Churn Prediction Model

Includes:

- Customer churn probability
- Customer risk classification
- Model performance metrics
- Feature importance analysis
- Risk distribution summary

## Dashboard Preparation

The datasets created in this notebook will support a Power BI dashboard designed to analyse:

- Overall churn performance
- Revenue impact of churn
- High-risk customers
- Key churn drivers
- Retention opportunities

## Business Outcome

The final dashboard will help stakeholders identify customers at risk of leaving and support data-driven retention strategies.

## Check Available Project Files

This notebook prepares the customer churn analysis outputs for Power BI.

Before loading the datasets, we will confirm that all required CSV files from the previous notebooks are available.

The files include:
- Customer data from Notebook 01
- Machine learning outputs from Notebook 04

These datasets will be transformed into Power BI-ready reporting tables.

## Import Required Libraries

Before loading any datasets, we need to import the Python libraries required in this notebook.

Pandas will allow us to load, inspect, and export our datasets for Power BI.

In [1]:
import pandas as pd

## Load the Final Customer Dataset

The final customer dataset was created and cleaned in Notebook 01. In this notebook, we will load the dataset so it can be used to prepare files for Power BI.

Loading the dataset ensures that all visualisations and business insights are based on the same validated data used throughout the project.

In [2]:
customer_df = pd.read_csv(
    "/kaggle/input/datasets/neelamsingh1987/customer-churn-dataset/customer_churn_final.csv"
)

customer_df.head()

,customer_id,signup_date,region,age_group,subscription_type,monthly_revenue,tenure_months,monthly_login_count,average_session_time_minutes,features_used,last_login_days_ago,complaint_count,response_time_hours,resolution_time_hours,customer_satisfaction_score,churn
0,10001,2023-01-31,London,60+,Professional,79,35,19.666667,28.124427,5.083333,29.666667,0.0,0.000000,0.000000,10.0,0
1,10002,2023-12-30,Leeds,18-25,Professional,79,24,14.583333,24.804342,5.833333,34.166667,2.0,13.014601,56.085322,9.0,0
2,10003,2022-05-10,Bristol,26-35,Basic,29,44,14.333333,24.192618,4.916667,30.250000,1.0,4.425014,6.192709,7.0,0
3,10004,2023-07-18,London,18-25,Basic,29,29,17.083333,22.674429,5.416667,26.583333,0.0,0.000000,0.000000,10.0,0
4,10005,2023-02-04,Manchester,60+,Basic,29,35,10.333333,24.052414,4.500000,28.083333,3.0,22.489549,82.144367,9.0,0

## Check Dataset Structure

Before preparing files for Power BI, we need to confirm the structure of the dataset.

This check allows us to verify:

- The number of customers included
- The number of columns available
- The data types of each field

This ensures the dataset is ready for dashboard development.

In [3]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   10000 non-null  int64
 1   signup_date                   10000 non-null  object
 2   region                        10000 non-null  object
 3   age_group                     10000 non-null  object
 4   subscription_type             10000 non-null  object
 5   monthly_revenue               10000 non-null  int64
 6   tenure_months                 10000 non-null  int64
 7   monthly_login_count           10000 non-null  float64
 8   average_session_time_minutes  10000 non-null  float64
 9   features_used                 10000 non-null  float64
 10  last_login_days_ago           10000 non-null  float64
 11  complaint_count               10000 non-null  float64
 12  response_time_hours           10000 non-null  float64
 13  resolution_time_hours         10000 non-null  float64
 14  customer_satisfaction_score   10000 non-null  float64
 15  churn                         10000 non-null  int64
dtypes: float64(8), int64(4), object(4)
memory usage: 1.2+ MB

## Check Dataset Size

We will confirm the number of rows and columns in the dataset.

This verifies that the Power BI dashboard will use the complete customer population analysed in the previous notebooks.

In [4]:
customer_df.shape

(10000, 16)

## Convert Signup Date to Date Format

The signup_date column is currently stored as text.

Converting it into a proper date format allows Power BI to recognise it as a date field and enables future analysis such as customer acquisition trends and signup timelines.

In [5]:
customer_df["signup_date"] = pd.to_datetime(
    customer_df["signup_date"]
)

customer_df.dtypes

customer_id                              int64
signup_date                     datetime64[ns]
region                                  object
age_group                               object
subscription_type                       object
monthly_revenue                          int64
tenure_months                            int64
monthly_login_count                    float64
average_session_time_minutes           float64
features_used                          float64
last_login_days_ago                    float64
complaint_count                        float64
response_time_hours                    float64
resolution_time_hours                  float64
customer_satisfaction_score            float64
churn                                    int64
dtype: object

In [6]:
customer_df.to_csv(
    "customer_churn_final_powerbi.csv",
    index=False
)

print("Customer dataset exported successfully.")

Customer dataset exported successfully.

## Verify Exported File

We will confirm that the CSV file has been created successfully before moving to the next dataset.

In [7]:
import os

os.path.exists("customer_churn_final_powerbi.csv")

True

## Locate Machine Learning Output Files

The machine learning outputs were exported from Notebook 04 and attached as a new Kaggle dataset.

We will identify the correct file location before loading the datasets into this notebook.

In [8]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        print(os.path.join(root, file))

/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/customer_churn_final.csv
/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/customer_risk_predictions.csv
/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/risk_summary.csv
/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/feature_importance.csv
/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/model_comparison.csv
/kaggle/input/datasets/neelamsingh1987/customer-churn-dataset/customer_churn_final.csv
/kaggle/input/datasets/neelamsingh1987/customer-churn-dataset/customer_churn_analytics.db

In [9]:
customer_risk = pd.read_csv(
    "/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/customer_risk_predictions.csv"
)

customer_risk.head()

   customer_id  churn_probability  actual_churn risk_category
0        10001               0.00             0      Low Risk
1        10002               0.00             0      Low Risk
2        10003               0.00             0      Low Risk
3        10004               0.00             0      Low Risk
4        10005               0.01             0      Low Risk

## Validate Customer Risk Predictions Dataset

The customer risk prediction table contains the machine learning output generated in Notebook 04.

This validation step confirms that customer-level predictions are correctly loaded before integrating the data into Power BI.

The table will support:
- High-risk customer identification
- Retention targeting
- Customer risk segmentation

In [10]:
customer_risk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        10000 non-null  int64
 1   churn_probability  10000 non-null  float64
 2   actual_churn       10000 non-null  int64
 3   risk_category      10000 non-null  object
dtypes: float64(1), int64(2), object(1)
memory usage: 312.6+ KB

In [11]:
customer_risk.shape

(10000, 4)

## Load Feature Importance Data

The feature importance dataset was generated during the machine learning stage.

It identifies the variables that contributed most to the churn prediction model.

This information will be used in Power BI to highlight the main factors influencing customer churn.

In [12]:
feature_importance = pd.read_csv(
    "/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/feature_importance.csv"
)

feature_importance.head()

                       Feature  Importance
0                features_used    0.251289
1          monthly_login_count    0.229130
2          last_login_days_ago    0.183059
3              complaint_count    0.162343
4  customer_satisfaction_score    0.132212

## Load Model Comparison Data

The model comparison dataset contains the performance results from the machine learning experiments completed in Notebook 04.

It compares different classification models based on:

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

This table will support transparency around the selected churn prediction model.

In [13]:
model_comparison = pd.read_csv(
    "/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/model_comparison.csv"
)

model_comparison.head()

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression    0.9385   0.858871  0.707641  0.775956  0.973627
1        Random Forest    1.0000   1.000000  1.000000  1.000000  1.000000
2    Gradient Boosting    1.0000   1.000000  1.000000  1.000000  1.000000

## Load Risk Summary Data

The risk summary dataset provides an overview of customer risk categories generated from the churn prediction model.

It summarises the number of customers classified as:

- Low Risk
- Medium Risk
- High Risk

This table will support dashboard visuals showing customer risk distribution and retention priorities.

In [14]:
risk_summary = pd.read_csv(
    "/kaggle/input/datasets/neelamsingh1987/customer-churn-powerbi-dashboard-data/risk_summary.csv"
)

risk_summary.head()

  Risk Category  Customer Count
0      Low Risk            8496
1     High Risk            1503
2   Medium Risk               1

## Validate Power BI Preparation Datasets

Before creating the Power BI dashboard, we will perform a final validation of all prepared datasets.

This ensures that the reporting tables contain the correct structure and information required for dashboard development.

In [15]:
datasets = {
    "Customer Dataset": customer_df,
    "Customer Risk Predictions": customer_risk,
    "Feature Importance": feature_importance,
    "Model Comparison": model_comparison,
    "Risk Summary": risk_summary
}

for name, data in datasets.items():
    print(name)
    print("Shape:", data.shape)
    print("----------------------")

Customer Dataset
Shape: (10000, 16)
----------------------
Customer Risk Predictions
Shape: (10000, 4)
----------------------
Feature Importance
Shape: (21, 2)
----------------------
Model Comparison
Shape: (3, 6)
----------------------
Risk Summary
Shape: (3, 2)
----------------------

## Create Customer Power BI Master Table

The customer dataset and machine learning prediction dataset are combined to create a single customer-level reporting table.

This master table will contain both historical customer information and predicted churn risk.

The table will be used as the main data source for Power BI customer analysis.

In [16]:
customer_powerbi = customer_df.merge(
    customer_risk,
    on="customer_id",
    how="left"
)

customer_powerbi.head()

,customer_id,signup_date,region,age_group,subscription_type,monthly_revenue,tenure_months,monthly_login_count,average_session_time_minutes,features_used,last_login_days_ago,complaint_count,response_time_hours,resolution_time_hours,customer_satisfaction_score,churn,churn_probability,actual_churn,risk_category
0,10001,2023-01-31,London,60+,Professional,79,35,19.666667,28.124427,5.083333,29.666667,0.0,0.000000,0.000000,10.0,0,0.00,0,Low Risk
1,10002,2023-12-30,Leeds,18-25,Professional,79,24,14.583333,24.804342,5.833333,34.166667,2.0,13.014601,56.085322,9.0,0,0.00,0,Low Risk
2,10003,2022-05-10,Bristol,26-35,Basic,29,44,14.333333,24.192618,4.916667,30.250000,1.0,4.425014,6.192709,7.0,0,0.00,0,Low Risk
3,10004,2023-07-18,London,18-25,Basic,29,29,17.083333,22.674429,5.416667,26.583333,0.0,0.000000,0.000000,10.0,0,0.00,0,Low Risk
4,10005,2023-02-04,Manchester,60+,Basic,29,35,10.333333,24.052414,4.500000,28.083333,3.0,22.489549,82.144367,9.0,0,0.01,0,Low Risk

In [17]:
customer_powerbi.shape

(10000, 19)

## Validate Customer Risk Information

After merging the customer dataset with the machine learning predictions, we will verify that the churn probability and risk classification fields have been added correctly.

This ensures the Power BI customer table contains both historical and predictive information.

In [18]:
customer_powerbi[
    [
        "customer_id",
        "churn",
        "churn_probability",
        "actual_churn",
        "risk_category"
    ]
].head()

   customer_id  churn  churn_probability  actual_churn risk_category
0        10001      0               0.00             0      Low Risk
1        10002      0               0.00             0      Low Risk
2        10003      0               0.00             0      Low Risk
3        10004      0               0.00             0      Low Risk
4        10005      0               0.01             0      Low Risk

## Validate Customer Risk Distribution

The customer master table now contains machine learning risk predictions.

We will review the distribution of customers across risk categories to confirm that the prediction results have been correctly integrated.

In [19]:
customer_powerbi["risk_category"].value_counts()

risk_category
Low Risk       8496
High Risk      1503
Medium Risk       1
Name: count, dtype: int64

## Calculate Dashboard KPI Metrics

The Power BI dashboard will include key performance indicators (KPIs) that provide an executive overview of customer churn performance.

These metrics summarise customer retention, financial impact, and customer risk exposure.

In [20]:
total_customers = customer_powerbi["customer_id"].nunique()

churned_customers = customer_powerbi["churn"].sum()

churn_rate = (churned_customers / total_customers) * 100

total_monthly_revenue = customer_powerbi["monthly_revenue"].sum()

high_risk_customers = (
    customer_powerbi["risk_category"] == "High Risk"
).sum()

revenue_at_risk = customer_powerbi.loc[
    customer_powerbi["risk_category"] == "High Risk",
    "monthly_revenue"
].sum()


print("Total Customers:", total_customers)
print("Churned Customers:", churned_customers)
print("Churn Rate:", round(churn_rate, 2), "%")
print("Total Monthly Revenue: £", total_monthly_revenue)
print("High Risk Customers:", high_risk_customers)
print("Revenue At Risk: £", revenue_at_risk)

Total Customers: 10000
Churned Customers: 1504
Churn Rate: 15.04 %
Total Monthly Revenue: £ 733000
High Risk Customers: 1503
Revenue At Risk: £ 110337

## Export Final Power BI Customer Master Table

The merged customer table combines customer information with machine learning churn predictions.

This final table will be used as the primary data source for Power BI customer-level analysis.

In [21]:
customer_powerbi.to_csv(
    "customer_powerbi_master.csv",
    index=False
)

print("Customer Power BI master table exported successfully.")

feature_importance.to_csv(
    "feature_importance.csv",
    index=False
)

model_comparison.to_csv(
    "model_comparison.csv",
    index=False
)

risk_summary.to_csv(
    "risk_summary.csv",
    index=False
)

print("Supporting Power BI tables exported successfully.")

Customer Power BI master table exported successfully.
Supporting Power BI tables exported successfully.

## Final Power BI Dataset Check

Before connecting the datasets to Power BI, we confirm that all required dashboard files are available.

This ensures a smooth transition from Python analysis to Power BI reporting.

In [22]:
import os

files = [
    "customer_powerbi_master.csv",
    "feature_importance.csv",
    "model_comparison.csv",
    "risk_summary.csv"
]

for file in files:
    print(file, ":", os.path.exists(file))

customer_powerbi_master.csv : True
feature_importance.csv : True
model_comparison.csv : True
risk_summary.csv : True